## Missing Data

In [39]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [40]:
data = pd.read_csv('Data.csv')
data.head()

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes

In [41]:
# independeny variable
# X = data.iloc[: , 1 : 3].values ## all rows, columns : 1 - 2
X = data.iloc[: , :-1].values ## remove last column

#dependent varible
y = data.iloc[ :, 3].values #all rows, 2nd column

#### Taking care of missing data

In [53]:
from sklearn.preprocessing import Imputer

# by default : 'mean' --> we can also take modeia, most_frequent
imputer = Imputer(missing_values = 'NaN', strategy = 'mean', axis = 0) # axis = 0 --> means along column, axis = 1 : along rows
imputer = imputer.fit(X[ :, 1:3])
X[:, 1:3] = imputer.transform(X[:, 1:3])

X[0]

C:\Users\Saurabh\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:58: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)


array([1.0e+00, 0.0e+00, 0.0e+00, 4.4e+01, 7.2e+04])

## Categorical Data
In the current dataset. 'country' and 'purchased' are Caterogical data, so we enconde that.

In [43]:
from sklearn.preprocessing import LabelEncoder

labelencoder_X = LabelEncoder()
X[:, 0] = labelencoder_X.fit_transform(X[: , 0])

In [44]:
X[0:2, :-1]

array([[0, 44.0],
       [2, 27.0]], dtype=object)

#### The Problem here:
The problem with the dataset now is, since the ML models are equations, so specifying countries as 0, 1, 2 in the data
might give the model a fell that france > germany > spain , w.r.t 0 > 1 > 2  **This happpens in case of Independent varible**<br>
**In case of Dependent variable ( y )** : we cn use LabelEncoder, since the ML model knows there need not be any order.

#### Solution:
Use dummy variable    

In [45]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

labelencoder_X = LabelEncoder()
X[:, 0] = labelencoder_X.fit_transform(X[: , 0])
onehotencoder = OneHotEncoder(categorical_features = [0])
X = onehotencoder.fit_transform(X).toarray()

X[0]

C:\Users\Saurabh\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:368: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Users\Saurabh\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:390: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


array([1.0e+00, 0.0e+00, 0.0e+00, 4.4e+01, 7.2e+04])

In [46]:
# In case of Dependent variable
labelencoder_y = LabelEncoder()
y = labelencoder_y.fit_transform(y)
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

## Splitting the Data into train and test
In any ML model, we need to seprarate pur data into train fnd test sets.<br>

In [47]:
from sklearn.model_selectionimport train_test_split
X_train, X_test, y_train, y_est = train_test_split(X, y, test_size = 0.2) #test size = 0.2 = 20% of data in test_size

## Feature Scaling
Consider the columns 'age' and 'Salary', we can see that if we plot these on a graph, then square of 'Salary' will dominate always, and the square of 'age' might get ignores, as it's too less than the former.<br>

Therefore, we need to feature scale these parameters in a way that there's not too much diff between their squared values.

In [48]:
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.fit_transform(X_test)


In [52]:
X_train[0] #no, we all the values are between -1 and +1

array([-1.        ,  1.29099445, -0.37796447,  0.14632696, -0.16029878])